/// Indented printing
Class Excel.PageMargins Extends (%RegisteredObject, %XML.Adaptor) [ Inheritance = right ]
{

Property Bottom As %Integer(XMLNAME = "x:Bottom", XMLPROJECTION = "ATTRIBUTE");

Property Left As %Integer(XMLNAME = "x:Left", XMLPROJECTION = "ATTRIBUTE");

Property Right As %Integer(XMLNAME = "x:Right", XMLPROJECTION = "ATTRIBUTE");

Property Top As %Integer(XMLNAME = "x:Top", XMLPROJECTION = "ATTRIBUTE");

}
